services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - demo-network
    env_file:
      - ./backend/.env
    environment:
      MONGO_DB_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - demo-network
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api/v1

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - demo-network
    volumes:
      - mongo-data:/data/db  

networks:
  demo-network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally