services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - demo-network
    environment:
      MONGO_URI: mongodb://mongodb:27017/sacred-hearts
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - demo-network

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - demo-network
    volumes:
      - mongo-data:/data/db  

networks:
  demo-network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally