# Generated by Django 3.2.19 on 2023-12-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
