# Generated by Django 3.2.19 on 2023-12-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20231229_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
