# Generated by Django 3.2.19 on 2023-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_alter_movies_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('SCIFi', 'SCiFI'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='video_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
