# Generated by Django 3.2.19 on 2023-12-29 17:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_auto_20231229_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('SCIFi', 'SCiFI'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery')], default='Fantasy', max_length=100),
        ),
    ]
