# Generated by Django 3.2.19 on 2023-12-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_alter_movies_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
