# Generated by Django 3.2.19 on 2023-12-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_alter_movies_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genres',
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='thumbnail',
            field=models.FileField(upload_to='Movies app'),
        ),
    ]
