# Generated by Django 3.2.19 on 2023-12-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0009_auto_20231230_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='Movies app'),
        ),
    ]
