# Generated by Django 3.2.19 on 2023-12-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_alter_movies_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='Movies_app/'),
        ),
    ]
