# Generated by Django 3.2.19 on 2023-12-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_alter_movies_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('SCIFi', 'SCiFI'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery')], default='Fantasy', max_length=100),
        ),
    ]
