# Generated by Django 3.2.19 on 2023-12-29 19:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_movies_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='sample_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sample_video'),
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='trailer'),
        ),
    ]
