# Generated by Django 3.2.19 on 2023-12-29 20:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0015_auto_20231230_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='sample_video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='Movies_app/sample_videos/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='Movies_app/trailers/'),
        ),
    ]
