# Generated by Django 3.2.19 on 2023-12-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0016_auto_20231230_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='video_url',
        ),
    ]
