# Generated by Django 3.2.19 on 2024-01-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0017_remove_movies_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('SCIFi', 'SCiFI'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Comedy', 'Comedy')], default='Fantasy', max_length=100),
        ),
    ]
